import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { SiteHeader } from "@/components/ui/site-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`antialiased @container/main`}>
        <SiteHeader />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
